services:
  mysql:
    image: mysql:8.0
    container_name: fastfood-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fastfood
      MYSQL_TEST_DATABASE: fastfood_test
      MYSQL_USER: user-admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - local-network
    healthcheck:
      test: /usr/bin/mysql -uroot -prootpassword -e "SHOW DATABASES"

  adminer:
    image: adminer
    container_name: fastfood-adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - local-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastfood-app
    environment:
        - MYSQL_URL=jdbc:mysql://mysql:3306/fastfood
        - MERCADO_PAGO_ACCESS_TOKEN=tokendoapimercadopago
        - MERCADO_PAGO_DEFAULT_PAYER_EMAIL=email
        - TECHFOOD_API_URL=urldaapi
    ports:
      - "8081:8081"
    networks:
      - local-network
    depends_on:
      mysql:
        condition: service_healthy

#  web:
#    image: fastfood-app  # Certifique-se de que "fastfood" é o nome da imagem correta
#    container_name: fastfood-web
#    environment:
#      - MYSQL_URL=jdbc:mysql://mysql:3306/fastfood
#    ports:
#      - "8082:8081"
#    networks:
#      - webnet
#      - local-network
#    depends_on:
#      app:
#        condition: service_started
#
#  ngrok:
#    image: wernight/ngrok
#    container_name: fastfood-ngrok
#    command: ngrok http web:8081  # A sintaxe correta inclui "ngrok" antes de "http"
#    environment:
#      - NGROK_AUTHTOKEN=2mXUXDvPrS7kqhqHtCNw6NRCcXB_BsD3rvuGCPkce3JJ7Mji  # Seu token de autenticação do ngrok
#    ports:
#      - "4040:4040"  # Expondo o dashboard do ngrok localmente
#    networks:
#      - webnet

networks:
  local-network:
    driver: bridge

#  webnet:
#    driver: bridge
