name: Fastfood CI.

on: [workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'maven'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Extract artifactId from pom.xml
      id: extract-artifact-id
      run: echo "ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV

    - name: Run SonarQube analysis
      run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
       -Dsonar.projectKey=${{ vars.ARTIFACT_ID }} 
       -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} 
       -Dsonar.host.url=${{ vars.SONAR_HOST_URL }} 
       -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    # - name: Set up SonarQube Scanner
    #   uses: sonarsource/sonarcloud-github-action@v1
    #   with:
    #     sonarToken: ${{ secrets.SONAR_TOKEN }}
    #     args: >
    #       -Dsonar.projectKey=${{ env.ARTIFACT_ID }}
    #       -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
    #       -Dsonar.host.url=${{ env.SONAR_HOST_URL }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get short commit hash
      id: vars
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.COMMIT_HASH }} .

    - name: Push Docker image
      run: docker push ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ env.COMMIT_HASH }}